/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_aiknow_basicandroid_androidso_NativeLog */

#ifndef _Included_cc_aiknow_basicandroid_androidso_NativeLog
#define _Included_cc_aiknow_basicandroid_androidso_NativeLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_aiknow_basicandroid_androidso_NativeLog
 * Method:    log
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_aiknow_basicandroid_androidso_NativeLog_log
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
